In [1]:
import numpy as np 

probabilities = np.array([0.1, 0.2, 0.3, 0.4])

np.log(probabilities)

array([-2.30258509, -1.60943791, -1.2039728 , -0.91629073])

In [2]:
np.log([0.1])

array([-2.30258509])

In [3]:
np.log([0.1, 0.2])

array([-2.30258509, -1.60943791])

In [4]:
np.log([0.1, 0.2, 0.3])

array([-2.30258509, -1.60943791, -1.2039728 ])